#
# Copyright 2014-2015, BPaul
#

# This file is generated by device/sony/aoba/setup-makefiles.sh

LOCAL_STEM := aoba_noril/device-partial.mk

$(call inherit-product-if-exists, vendor/sony/$(LOCAL_STEM))
